// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1R2caYG6twmqGZgcp92a_ZHRkHA1BKoI',
    appId: '1:1084331763047:web:9cc2c72f287032a335fbc2',
    messagingSenderId: '1084331763047',
    projectId: 'hack-a-addict',
    authDomain: 'hack-a-addict.firebaseapp.com',
    storageBucket: 'hack-a-addict.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5R5tUaDs9RupC2_Mm9rQq1zC3xIKRPc',
    appId: '1:1084331763047:android:c3a7a970e4db5cc835fbc2',
    messagingSenderId: '1084331763047',
    projectId: 'hack-a-addict',
    storageBucket: 'hack-a-addict.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-k_bCEnTnMLk_Ae9yOzq6po1EwH4n1o',
    appId: '1:1084331763047:ios:e624510ca85e97f735fbc2',
    messagingSenderId: '1084331763047',
    projectId: 'hack-a-addict',
    storageBucket: 'hack-a-addict.firebasestorage.app',
    iosBundleId: 'com.example.hackaddict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-k_bCEnTnMLk_Ae9yOzq6po1EwH4n1o',
    appId: '1:1084331763047:ios:e624510ca85e97f735fbc2',
    messagingSenderId: '1084331763047',
    projectId: 'hack-a-addict',
    storageBucket: 'hack-a-addict.firebasestorage.app',
    iosBundleId: 'com.example.hackaddict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1R2caYG6twmqGZgcp92a_ZHRkHA1BKoI',
    appId: '1:1084331763047:web:101bae1059ed6d0b35fbc2',
    messagingSenderId: '1084331763047',
    projectId: 'hack-a-addict',
    authDomain: 'hack-a-addict.firebaseapp.com',
    storageBucket: 'hack-a-addict.firebasestorage.app',
  );
}
