// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDvsmVqlc7Q9096Diy6ucjgoOgJHBYVs',
    appId: '1:906924248778:web:5a9428f7be17ffa0ddee33',
    messagingSenderId: '906924248778',
    projectId: 'react-5a257',
    authDomain: 'react-5a257.firebaseapp.com',
    storageBucket: 'react-5a257.appspot.com',
    measurementId: 'G-X79ET3ZYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyJQBs-3Cf5aAwnWEg0bhSzdYPDYr76A',
    appId: '1:906924248778:android:4f34256df15b5f86ddee33',
    messagingSenderId: '906924248778',
    projectId: 'react-5a257',
    storageBucket: 'react-5a257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwfl0usWEihD6FZSF30x_pMIuOvwfwL20',
    appId: '1:906924248778:ios:a721f36beccb8a45ddee33',
    messagingSenderId: '906924248778',
    projectId: 'react-5a257',
    storageBucket: 'react-5a257.appspot.com',
    iosBundleId: 'com.example.hackaddict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwfl0usWEihD6FZSF30x_pMIuOvwfwL20',
    appId: '1:906924248778:ios:a721f36beccb8a45ddee33',
    messagingSenderId: '906924248778',
    projectId: 'react-5a257',
    storageBucket: 'react-5a257.appspot.com',
    iosBundleId: 'com.example.hackaddict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN_PPGsKvlscP25KnWL4j-M-npmHa6n60',
    appId: '1:906924248778:web:71a69a71d61741baddee33',
    messagingSenderId: '906924248778',
    projectId: 'react-5a257',
    authDomain: 'react-5a257.firebaseapp.com',
    storageBucket: 'react-5a257.appspot.com',
    measurementId: 'G-25SGN43QW8',
  );

}